name: Pytest weekly

on: push
# on:
#   schedule:
#   - cron: 59 22 * * 5   # Schedule triggers every Friday at 22:59 UTC

jobs:
  test:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python: ['3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest

    - name: Install package
      working-directory: .
      run: |
        python -m pip install git+ssh://git@github.com/pydykit/pydykit.git@postprocessing_advanced#egg=pydykit

    - name: Pytest
      working-directory: .
      run: |
        pytest -vv --runslow
